
package wdslbankaaaws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BankAAAWSImplService", targetNamespace = "http://bankaaaws/", wsdlLocation = "http://localhost:8081/BankAAAWS?wsdl")
public class BankAAAWSImplService
    extends Service
{

    private final static URL BANKAAAWSIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException BANKAAAWSIMPLSERVICE_EXCEPTION;
    private final static QName BANKAAAWSIMPLSERVICE_QNAME = new QName("http://bankaaaws/", "BankAAAWSImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8081/BankAAAWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BANKAAAWSIMPLSERVICE_WSDL_LOCATION = url;
        BANKAAAWSIMPLSERVICE_EXCEPTION = e;
    }

    public BankAAAWSImplService() {
        super(__getWsdlLocation(), BANKAAAWSIMPLSERVICE_QNAME);
    }

    public BankAAAWSImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BANKAAAWSIMPLSERVICE_QNAME, features);
    }

    public BankAAAWSImplService(URL wsdlLocation) {
        super(wsdlLocation, BANKAAAWSIMPLSERVICE_QNAME);
    }

    public BankAAAWSImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BANKAAAWSIMPLSERVICE_QNAME, features);
    }

    public BankAAAWSImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BankAAAWSImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BankAAAWS
     */
    @WebEndpoint(name = "BankAAAWSImplPort")
    public BankAAAWS getBankAAAWSImplPort() {
        return super.getPort(new QName("http://bankaaaws/", "BankAAAWSImplPort"), BankAAAWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BankAAAWS
     */
    @WebEndpoint(name = "BankAAAWSImplPort")
    public BankAAAWS getBankAAAWSImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://bankaaaws/", "BankAAAWSImplPort"), BankAAAWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BANKAAAWSIMPLSERVICE_EXCEPTION!= null) {
            throw BANKAAAWSIMPLSERVICE_EXCEPTION;
        }
        return BANKAAAWSIMPLSERVICE_WSDL_LOCATION;
    }

}
